### ISSUE TITLE
Once unsubscribed, can't resubscribe

### ISSUE THREAD

**Issue by davidkryzaniak** [jgulledge19/GroupEletters#26]
Hi,

I think I might have found a bug dealing with unsubscribing and then resubscribing. On the backend, removing a group from a given user works, but the change is not reflected in the GUI (If you actually go into the database, you can see that `receive_email` is set to an N. The GUI always says they are in the group). Because the GUI thinks the user is already in the group, they can't be added back into the group. 

I've tested this on 2 different servers, both running Modx Revo 2.2.1 and RC3 of GroupEletters. Any help would be greatly appreciated.

**Comment by jgulledge19** [comment]
See #29
