### ISSUE TITLE
Send mals with SMPT

### ISSUE THREAD

**Issue by navtsi** [jgulledge19/GroupEletters#35]
The signin mail will not be sent. it seams to be a problem with the SMTP. My provider only allows sending emails with SMTP authentification. For my contact form I configured the SMTP in the MODx system settings, but I cannot set them for the ELetter signin mail. Is there a way to use the MODx system settings, or to configure SMTP settings for Eletter?

**Comment by jgulledge19** [comment]
See this documentation: https://modxcloud.com/userguide/using-modx-cloud/email/gmail-or-smtp-for-sending-email.html on setting up SMTP.
