### ISSUE TITLE
Component does not work

### ISSUE THREAD

**Issue by t3mnikov** [jgulledge19/GroupEletters#40]
Does not work on MODX 2.5.1, PHP 7.0.8, MySQL 5.7. does not send a test email and there are no errors, the log is empty

**Comment by t3mnikov** [comment]
I found errors on these lines:
[https://github.com/jgulledge19/GroupEletters/blob/master/core/components/eletters/model/eletters/eletternewsletters.class.php#L351](line 351)
[https://github.com/jgulledge19/GroupEletters/blob/master/core/components/eletters/model/eletters/eletternewsletters.class.php#L382](line 382)

**Comment by izenn** [comment]
same here with modx 2.5.1 php 7.0.12 and mariadb 10.1.18; however i get the following error:
PHP Fatal error:  'continue' not in the 'loop' or 'switch' context in /srv/http/wolfpack/public/core/components/eletters/model/csstoinline/css_to_inline_styles.php on line 353

also, when send test e-mail is checked the page never saves and just keeps looping.  the error is from the cronmanager

**Comment by izenn** [comment]
If i cancel the save and try to run cron i get the following error:
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /srv/http/wolfpack/public/core/components/eletters/model/eletters/eletternewsletters.class.php:338
Stack trace:
#0 /srv/http/wolfpack/public/core/components/eletters/model/eletters/eletternewsletters.class.php(208): EletterNewsletters->_createELetter(true)
#1 /srv/http/wolfpack/public/core/components/eletters/model/eletters/eletternewsletters.class.php(152): EletterNewsletters->sendOne(Object(EletterSubscribers_mysql))
#2 /srv/http/wolfpack/public/core/components/eletters/model/eletters/eletters.class.php(112): EletterNewsletters->sendList('20', '10')
#3 /srv/http/wolfpack/public/core/cache/includes/elements/modsnippet/25.include.cache.php(11): Eletters->processQueue()
#4 /srv/http/wolfpack/public/core/model/modx/modscript.class.php(70): include('/srv/http/wolfp...')
#5 /srv/http/wolfpack/public/assets/components/cronmanager/cron.php(65): modScript->process()
#6 {main}
  thrown in /srv/http/wolfpack/public/core/components/eletters/model/eletters/eletternewsletters.class.php on line 338
```

**Comment by izenn** [comment]
I just figured this one out and created a pull request -- to fix it manually, edit line 353 and change the "continue" to "return"

**Comment by jgulledge19** [comment]
Looks like this included package is way behind: https://packagist.org/packages/tijsverkoyen/css-to-inline-styles#1.3.0. I probably could update it to 1.3.0 with out any issues, but still could need this fix for PHP7. To update to 1.3.0 download it and then find and copy over this file: https://github.com/jgulledge19/GroupEletters/blob/master/core/components/eletters/model/csstoinline/css_to_inline_styles.php

**Comment by jgulledge19** [comment]
I have merged the pull request and updated the MODX package to 1.1.1pl
